### PR TITLE
fixing kmeans when tensor is not default tensor type. Fixes #24

### LINKED ISSUE #24: kmeans breaks on FloatTensor with unhelpful error message
Was tearing my hair out trying to debug this: try doing  

    unsup.kmeans(torch.FloatTensor(100,100), 20, 20, 20)

You'll get

    unsup.kmeans(torch.FloatTensor(100,100), 20, 20, 20)
    bad argument #2 to '?' (number expected, got userdata)
    stack traceback:
            [C]: at 0x2aaaaad0ab00
            [C]: in function '__mul'
            /home/ml4133/distro/install/share/lua/5.1/unsup/kmeans.lua:72: in function 'kmeans'
            [string "k = unsup.kmeans(torch.FloatTensor(100,100), ..."]:1: in main chunk
            [C]: in function 'xpcall'
            /home/ml4133/distro/install/share/lua/5.1/trepl/init.lua:598: in function 'repl'
            ...133/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
            [C]: at 0x00406080

### PR DESCRIPTION
**Pull request by soumith**

### CODE REVIEW

File: kmeans.lua [hunk 1]
```diff
@@ -26,11 +26,9 @@ function unsup.kmeans(x, k, niter, batchsize, callback, verbose)
...
 
    -- some shortcuts
-   local sum = torch.sum
-   local max = torch.max
-   local pow = torch.pow
-   local randn = torch.randn
-   local zeros = torch.zeros
+   local sum = x.sum
+   local max = x.max
+   local pow = x.pow
```
Comment (deltheil) [inline kmeans.lua]: This introduces a bug since `x.pow` has for effect to modify in-place its first arg:

```Lua
local x   = torch.Tensor{1, 2, 3}
local pow = x.pow
local x2  = pow(x, 2)
print(x) --> {1, 4, 9} i.e x has been modified!
```

Instead of:

```Lua
local x   = torch.Tensor{1, 2, 3}
local pow = torch.pow
local x2  = pow(x, 2)
print(x) --> {1, 2, 3} i.e x is kept untouched
```
